### ISSUE TITLE
Change History Facet doesn't show Change log table

### ISSUE THREAD

**Issue by vishalsharma190596** [cap-js/change-tracking#169]
Hi Team,

We are using the Change Tracking plugin for our CAP project and the change tracking was working fine until recently.

Now we are not able to see the Change History table in the Facet at all the Entities where we have implemented Change tracking. It shows below error message stating it could not find the Presentation variant of Changes

![Image](https://github.com/user-attachments/assets/e6f676a7-a9dd-4bc8-b1fd-face94f1c349)

We are using the below dependencies and upgraded to the recently released 1.0.8 version of Change tracking, still we are facing this issue.

```
"@sap/cds": "^8",
"@cap-js/change-tracking": "^1.0.8",
"@sap/cds-dk": "^8"
```
This is a critical issue in a Production application in SAP so we would appreciate your support in resolving/identifying this issue.

Thanks & Regards,
Vishal Sharma

**Comment by T1mey** [comment]
same problem here... locally it's working, but deployed to CF it's showing the error shown above.

@nkaputnik 
@Sv7enNowitzki

**Comment by Sv7enNowitzki** [comment]
It seems another stakeholder is experiencing a similar issue. I would like to ping you to reference the workaround mentioned above. @rgadirov

**Comment by nkaputnik** [comment]
Hello @rgadirov and @vishalsharma190596 
we can now reproduce this issue and it looks like a bug in the build CLI of CAP. This will hopefully be resolved soon and should then be fixed by a new release of CAP itself, not the plugin itself.

Best,
Nick

**Comment by rgadirov** [comment]
Hello @nkaputnik 

thank you for your feedback, so which component of CAP itself should be updated? Is it the CAP CDS 8 version, the npm module, or what exactly? Can you differentiate the component?

Best regards
Rufat

**Comment by nkaputnik** [comment]
Hello,
as soon as this was fixed, I'll update here with the instructions. This won't happen over night, since the CAP team currently is busy with a new release, my assumption is, that it will be part of the next release.

Best,
Nick

**Comment by nkaputnik** [comment]
Update:
Bug is acknowledged by the compiler team, and a fix is underway.
Since the compiler is a central component to CAP, extensive testing is necessary, so this will take some time.
Expected timing right now: This will be available with the next major release (CDS9), which is expected to be released in 5 weeks from now, and additionally a downport to CDS8 shortly after that.
In then meantime, you should be able to test the fix already next week by simply installing CDS itself from main on github, if you are an SAP employee.

Best,
Nick

**Comment by varunmguptaa** [comment]
@nkaputnik 
Hey, just following up on the bug — the issue still seems to be there. Any update on the status?

![Image](https://github.com/user-attachments/assets/dfb4d10b-7d9a-4b93-9c2e-ac1d21e51ef1)

**Comment by nkaputnik** [comment]
Hello @varunmguptaa 
Compiler Team has confirmed tha the fix will be in the CDS9 major, which is scheduled for early June. After upgrading, nothing additionally will need to be done in the plugin or application itself.
Best,
Nick

**Comment by Sv7enNowitzki** [comment]
Hi

After CDS 8.9.3, they seem to have fixed this issue. The latest version is CDS 8.9.4. Please update your CDS version to the latest one. I have tested it on my side without any issues. Looking forward to your feedback.

Best Regards,
Wenjun

**Comment by Sv7enNowitzki** [comment]
Close the issue because it has been fixed by CDS.
