### ISSUE TITLE
Changelog for Entities containing associations as key

### ISSUE THREAD

**Issue by sandr0ne** [cap-js/change-tracking#51]
Hello Team,

currently we are facing an issue using the change log on entities which have associations as keys defined.
Some cases are even more complex, but real world scenarios.

We have one entity called MatrixCertificates which connects the keys of devisions with document types and adds a property called 'relevant'. Divisions are stored within the same project. Document types are not, they are part of a different micro-service in a different cap project according to our designed micro service architecture.

Please find below CDS model:

```JavaScript
@cds.persistence.journal
entity Divisions : CodeList {
  key division : String(20);
}

@readonly
entity DocumentTypes as projection on Doc.DocumentTypes;

entity MatrixCertificates {
  @assert.integrity: false key division     : Association to one Divisions;
  @assert.integrity: false key documentType : Association to one DocumentTypes;
                               relevant     : String(1) enum {
                                 a;
                                 b;
                                 c;
                               }
}
```

We would like to use change-log annotations like this:

```JavaScript
@changelog
@cds.persistence.journal
entity Divisions : CodeList {
  key division : String(20);
}

@readonly
entity DocumentTypes as projection on Doc.DocumentTypes;

@changelog
entity MatrixCertificates {
  @assert.integrity: false key division     : Association to one Divisions @changelog;
  @assert.integrity: false key documentType : Association to one DocumentTypes @changelog;
                               relevant     : String(1) enum {
                                 a;
                                 b;
                                 c;
                               };
}
```
Issue is, that at startup of the service following error occurs:
![image](https://github.com/cap-js/change-tracking/assets/4747321/690c07e7-8e50-4e6a-9c94-ab1381eb5fa7)

Are you aware about this behaviour? Is it foreseen to be fixed?

Thanks and best regards
Sandro

**Comment by nkaputnik** [comment]
Hello @sandr0ne 
we hope that this is fixed in the newest release which should be out somewhen today or tomorrow, depending on how long the release takes technically.

Best,
Nick

**Comment by sandr0ne** [comment]
Hey @nkaputnik,

thank you for taking this up. We've tested the latest version today. Unfortunately it is not solving the issue we had. We are just getting now different error messages for the same effected entities:
![image](https://github.com/cap-js/change-tracking/assets/4747321/ef48feed-8c38-4b84-a0ca-dcc3de5084d9)

Best regards
Sandro

**Comment by sandr0ne** [comment]
Hey @nkaputnik,

hope you are doing fine?
We've checked the latest version of the plugin again and still facing this issue mentioned in my last comment.
Would you be so kind to have a look into this topic again?

Thanks a lot and best regards
Sandro

**Comment by nkaputnik** [comment]
Hello @sandr0ne 
@Sv7enNowitzki  may be able to provide more input on this, but my understanding is, that a main limitation of the current design is, that we rely on a single GUID value as key for change tracking to work properly. 

Best,
Nick

**Comment by nkaputnik** [comment]
This will hopefully be fixed in the next release
